### PR TITLE
fixes tabs issue in non-Blink browsers

### LINKED ISSUE #104: Styleguide tabs only function in blink browsers
Chrome and Opera have properly functioning tabs in the style guide.  Tabs fail in other desktop browsers (tested: Safari latest, FF latest, IE11, Edge)

## Expected Behavior

Clicking tabs should change content shown (rendered html, React code, HTML code, or JSON)

## Current Behavior

Clicking tabs does not change content.  Only rendered HTML is ever visible, except in Chrome and Opera (Blink browsers)

## Possible Solution

Based on FF console error, code is itterating NodeLists using .forEach(); this is supported in Blink but not implemented in other browsers.  Solution is to use Array.prototype.split() or .splice().

I will submit a fix shortly.

### PR DESCRIPTION
**Pull request by stoff**
## Description

Tab switcher itterates over tabs and related content to set display classes on the affected tabs and content.  Elements were itterated in NodeLists using forEach(); this has not been implemented on NodeList in most browsers.
Fix was to call `Array.prototype.splice` on each NodeList before itteration.
Fixes #104 

## How Has This Been Tested?

Opened in affected browsers and verified I could switch tabs.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: source/styleguide.jsx [hunk 1]
```diff
@@ -32,7 +32,8 @@ const examplesItems = examples.map(e => e.querySelectorAll('.sg-example__tabs-it
 
 examplesTabs.forEach((tabset, i) => {
 	tabset.addEventListener('click', ev => {
-		examplesItems[i].forEach((item, j) => {
+		Array.prototype.slice.call(examplesItems[i]).forEach((item, j) => {
+			console.log(examplesSections[i][j], item);
```
Comment (elseloop) [inline source/styleguide.jsx]: Please clean up your stray console log.

**Comment by stoff** [comment]
de-logged, ready for re-review. go-to it.
